### ISSUE TITLE
azurerm_monitor_diagnostic_setting applies/updates every time

### ISSUE THREAD

**Issue by surlypants** [hashicorp/terraform-provider-azurerm#10857]
azurerm_monitor_diagnostic_setting applies (updates in place) _every_ time (at least when the target is log analytics) due to case-mismatch:

this has been happening for a while and persists into 2.50.0

```
  ~ resource "azurerm_monitor_diagnostic_setting" "ladiag" {
        id                         = "/subscriptions/XXX/resourceGroups/XXX/providers/Microsoft.Sql/servers/XXX/elasticPools/XXX|XXX"
      ~ log_analytics_workspace_id = "/subscriptions/XXX/resourceGroups/XXX/providers/Microsoft.OperationalInsights/workspaces/XXX" -> "/subscriptions/XXX/resourcegroups/XXX/providers/microsoft.operationalinsights/workspaces/XXX"
```

(the target resource (sql, app service, etc) is irrelevant)

**Comment by favoretti** [comment]
@surlypants Thank you for reporting this. Out of curiosity, are you referring to LAW id from a resource attribute or from a datasource attribute? I am seeing the same behavior in another resource, want to confirm whether my theory on how to fix this is correct.

**Comment by surlypants** [comment]
@favoretti  in our case, the id is sourced via a data call (all LAWs are harvested early in orchestration to be fed to dependent modules)

**Comment by favoretti** [comment]
@surlypants Thank you, that's what I thought. I'm already working on a fix for this, hang tight :)

**Comment by surlypants** [comment]
not sure if this is fixed....planning with 2.51.0 still shows:

```
      ~ log_analytics_workspace_id = "/subscriptions/XXX/resourceGroups/XXX/providers/Microsoft.OperationalInsights/workspaces/XXX" -> "/subscriptions/XXX/resourcegroups/XXX/providers/microsoft.operationalinsights/workspaces/XXX"
```

**Comment by favoretti** [comment]
@tombuildsstuff would this mean we need to enable state migration for data source too?

**Comment by surlypants** [comment]
@tombuildsstuff / @favoretti 

is a new issue needed so this doesn't fall off the radar?

to highlight the severity of this, the apply triggers a reset of a linux web app containers :( (and likely other production impacting side effects)

**Comment by tombuildsstuff** [comment]
@favoretti missed this - arguably the Diagnostic Setting Resource would need a state migration, although running the apply above should fix that for @surlypants?

**Comment by favoretti** [comment]
@tombuildsstuff My guess would be that the state should be updated with the proper casing without state migration, although since they are using a datasource, if that one was written to the state with wrong casing - maybe it's log analytics workspace data source that needs a state migration rather than resources using it as a reference? I see we added state migration to LAW resource, but not to the datasource.

**Comment by favoretti** [comment]
OTOH... I probably need to set up a test and see what returns what, I'm still getting lost in all these casing dances..

**Comment by surlypants** [comment]
I'll try 2.52 in my unit test with multi runs..

**Comment by favoretti** [comment]
@surlypants If you have an isolated test - please share the code, will save me some typing and I'll join in on debugging. :)

**Comment by surlypants** [comment]
the issue persists after an apply with 2.52 :|

**Comment by surlypants** [comment]
keep-alive

**Comment by surlypants** [comment]
wild and crazy theory (in process)

an apply from an OS that is truly case sensitive, corrects the state...

**Comment by favoretti** [comment]
If you could elaborate on this - I’m super curious. Thank you!

**Comment by surlypants** [comment]
it was a mighty theory, yet false


```
   ~ resource "azurerm_monitor_diagnostic_setting" "ladiag" {
        id                         = "/subscriptions/XXX/resourceGroups/sql-dev-rg/providers/Microsoft.Sql/servers/XXX|XXX"
      ~ log_analytics_workspace_id = "/subscriptions/XXX/resourceGroups/XXX/providers/Microsoft.OperationalInsights/workspaces/XXX" -> "/subscriptions/XXX/resourcegroups/XXX/providers/microsoft.operationalinsights/workspaces/XXX"
```

**Comment by techsun** [comment]
I believe you're experiencing a version of this issue, which contains the resolution I worked out. Would be great if the provider dealt with this better: https://github.com/terraform-providers/terraform-provider-azurerm/issues/11099

**Comment by AndriiChuhunkovSecurrency** [comment]
keep-alive

**Comment by moogly81** [comment]
The issue  persists with version 2.77.0
quick fix : replace

```
resource "azurerm_monitor_diagnostic_setting" "databricks_audit" {
   ...
  # Quick FIX:
  log_analytics_workspace_id = replace(replace(azurerm_log_analytics_workspace.***.id, "microsoft.operationalinsights", "Microsoft.OperationalInsights"), "resourcegroups", "resourceGroups")
  ...
```

**Comment by nes-achimg** [comment]
Just to add to the case.
We are experiencing similar problems with azurerm v2.85:

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.ls_999.module.vm_prbdsd2ci.azurerm_site_recovery_replicated_vm.vm_replication[0] will be updated in-place
  ~ resource "azurerm_site_recovery_replicated_vm" "vm_replication" {
        id                                        = "/subscriptions/xxx/resourceGroups/rg-prb-neu-backup/providers/Microsoft.RecoveryServices/vaults/rsv-prb-neu-vault/replicationFabrics/primary-fabric/replicationProtectionContainers/primary-protection-container/replicationProtectedItems/vm-prbdsd2ci"
        name                                      = "vm-prbdsd2ci"
      ~ target_network_id                         = "/subscriptions/xxx/resourcegroups/rg-prb-neu-network/providers/microsoft.network/virtualnetworks/vr-prb-neu-non_sap" -> "/subscriptions/xxx/resourceGroups/rg-prb-neu-network/providers/Microsoft.Network/virtualNetworks/vr-prb-neu-non_sap"
        # (11 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

**Comment by askldjd** [comment]
The issue persists with version 2.94.0

**Comment by tombuildsstuff** [comment]
The original issue here has since been resolved, please upgrade to the latest version of the Azure Provider (v2.99 at the time of writing) - for issues with other resources please upgrade to the latest version and if still encountering an issue then please open a new issue to track this specifically.
