### ISSUE TITLE
azurerm_monitor_diagnostic_setting: Casing Microsoft.OperationalInsights forces update

### ISSUE THREAD

**Issue by abij** [hashicorp/terraform-provider-azurerm#11099]
Terraform provider version: hashicorp/azurerm v2.52.0.

```
# azurerm_monitor_diagnostic_setting.databricks_audit will be updated in-place
  ~ resource "azurerm_monitor_diagnostic_setting" "databricks_audit" {
        id                         = "/subscriptions/***/resourceGroups/***/providers/Microsoft.Databricks/workspaces/***|audit-log-collector"
      ~ log_analytics_workspace_id = "/subscriptions/***/resourceGroups/***/providers/Microsoft.OperationalInsights/workspaces/***" -> "/subscriptions/***/resourcegroups/***/providers/microsoft.operationalinsights/workspaces/***"
        name                       = "audit-log-collector"
```

_Originally posted by @tombuildsstuff in https://github.com/terraform-providers/terraform-provider-azurerm/issues/10203#issuecomment-762028358_

I'm linking my LogAnalytics workspace: 

```
resource "azurerm_monitor_diagnostic_setting" "databricks_audit" {
  name                       = "audit-log-collector"
  target_resource_id         = module.databricks.workspace_id
  log_analytics_workspace_id = azurerm_log_analytics_workspace.***.id
# Quick FIX:
# log_analytics_workspace_id = replace(replace(azurerm_log_analytics_workspace.***.id, "microsoft.operationalinsights", "Microsoft.OperationalInsights"), "resourcegroups", "resourceGroups")
  # log blocks ... 
```

Diff: `Microsoft.OperationalInsights` vs `microsoft.operationalinsights`.
**NOTE also: `resourcegroups` vs `resourceGroups`**

**Comment by techsun** [comment]
In my case, this annoyance was related to proposed changes to other resources (`such as azurerm_monitor_diagnostic_setting`) that referenced an `azurerm_log_analytics_workspace`. I resolved this issue by removing and re-importing the `azurerm_log_analytics_workspace` resource carefully using the _exact casing_ of the original path provided in the plan (left of the "->")

**Comment by v4ld3r5** [comment]
We are having the same issue:
There's a `log_analytics_workspace` that was deployed using provider version `2.33.0`. Checked the state and as confirmed the whole `id` is lowcase.

Today, by using version `2.57.0`, we deployed an AKS cluster which references this workspace.
There's no problem at all, but running `plan` always complains about it.

Wouldn't be possible from the provider to ignore this casing difference?
Or was this maybe caused by a change on Microsoft's API?

**Comment by rstarov** [comment]
According to azurerm release notes this issue was fixed in version 2.51.0 (March 12, 2021)
https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/CHANGELOG-v2.md#2510-march-12-2021

**Comment by laughtonsm** [comment]
Same issue here too.  Log Analytics has been deployed using `2.60.0` of the provider.  Diagnostics Settings is using `2.63.0` The output from the Log Analytics resource has the correct camel case in the state file.  Doing a plan or apply on the diagnostics setting always triggers an update, wanting to change the case of the resource ID from camel case to lower case.

**Comment by abij** [comment]
Today with azurerm `2.70.0` the issue still exists.

Did you see my quickfix? In case you have scrolled down directly...

```terraform
resource "azurerm_monitor_diagnostic_setting" "databricks_audit" {
  name                       = "audit-log-collector"
  target_resource_id         = module.databricks.workspace_id
  # Quick FIX:
  log_analytics_workspace_id = replace(replace(azurerm_log_analytics_workspace.***.id, "microsoft.operationalinsights", "Microsoft.OperationalInsights"), "resourcegroups", "resourceGroups")
  # log blocks ... 
```

**Comment by tenletters10** [comment]
Was running into the same issue with the azurerm_monitor_diagnostic_setting resource updating in-place over and over and didn't even notice the uppercase issue going on until I found this thread. I am using the replace to make it camel case for the resource type to work around this bug too.

**Comment by tombuildsstuff** [comment]
This has since been fixed in the latest version of the Azure Provider - please upgrade to the latest version (2.99.0 at the time of writing).
