### ISSUE TITLE
Deletion of azurerm_firewall failing due to "UnsupportedMediaType"

### ISSUE THREAD

**Issue by j-chao** [hashicorp/terraform-provider-azurerm#14866]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.1.3
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.91.0

### Affected Resource(s)

* `azurerm_firewall`

### Terraform Configuration Files

```hcl
resource "azurerm_firewall_policy" "gateway" {
  name                = var.name
  resource_group_name = var.resource_group_name
  location            = var.location
  sku                 = "Standard"

  dns {
    proxy_enabled = true
  }

  depends_on = [var.firewall_depends_on]
}

resource "azurerm_firewall" "gateway" {
  name                = var.name
  location            = var.location
  resource_group_name = var.resource_group_name
  sku_name            = "AZFW_VNet"
  sku_tier            = "Standard"
  firewall_policy_id  = azurerm_firewall_policy.gateway.id
  zones               = ["1", "2", "3"]
  threat_intel_mode   = "Alert"

  ip_configuration {
    name                 = "configuration"
    subnet_id            = azurerm_subnet.firewall.id
    public_ip_address_id = azurerm_public_ip.firewall.id
  }

  depends_on = [var.firewall_depends_on, azurerm_firewall_policy.gateway]

  tags = var.tags
}

```

### Debug Output

https://gist.github.com/j-chao/97e5a332209d3026befdb744c2d039d3 

### Expected Behaviour

Azure Firewall resource should be successfully destroyed.

### Actual Behaviour

Terraform destroy failed.

### Steps to Reproduce

1. Create azure firewall resource with Terraform
2. Attempt to destroy with `terraform destroy ...`

**Comment by sinbai** [comment]
Hi @j-chao Thanks for reporting this issue. I can not repro this issue with the following steps 
1. terraform apply the tf config below:
```
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
	 version = "~> 2.91.0"
    }
  }
}
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-Elena02"
  location = "eastus"
}

resource "azurerm_virtual_network" "test" {
  name                = "acctestvirtnet1"
  address_space       = ["10.0.0.0/16"]
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
}

resource "azurerm_subnet" "firewall" {
  name                 = "AzureFirewallSubnet"
  resource_group_name  = azurerm_resource_group.test.name
  virtual_network_name = azurerm_virtual_network.test.name
  address_prefixes     = ["10.0.1.0/24"]
}

resource "azurerm_public_ip" "firewall" {
  name                = "acctestpip1"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  allocation_method   = "Static"
  sku                 = "Standard"
}


resource "azurerm_firewall_policy" "gateway" {
  name                = "elena2"
  resource_group_name = azurerm_resource_group.test.name
  location            = "eastus"
  sku                 = "Standard"

  dns {
    proxy_enabled = true
  }
}

resource "azurerm_firewall" "gateway" {
  name                = "elena22"
  location            = "eastus"
  resource_group_name = azurerm_resource_group.test.name
  sku_name            = "AZFW_VNet"
  sku_tier            = "Standard"
  firewall_policy_id  = azurerm_firewall_policy.gateway.id
  zones               = ["1", "2", "3"]
  threat_intel_mode   = "Alert"

  ip_configuration {
    name                 = "configuration"
    subnet_id            = azurerm_subnet.firewall.id
    public_ip_address_id = azurerm_public_ip.firewall.id
  }

  depends_on = [azurerm_firewall_policy.gateway]

}
```

2. terraform destroy after step1 complete. => Everything goes smoothly.

Could you provide the step-by-step repro steps that could help repro and troubleshooting?

**Comment by tombuildsstuff** [comment]
@j-chao thanks for reporting this, this is an upstream issue we're looking into.

**Comment by j-chao** [comment]
@tombuildsstuff just curious, what's the upstream issue?

**Comment by tombuildsstuff** [comment]
@j-chao internal upstream, not upstream-upstream - sorry - we're missing a Content-Type when sending this request for some reason (which is a bug) but appears to be a breaking behavioural change in the API, since this has been fine historically

**Comment by tombuildsstuff** [comment]
Fixed via #14927

**Comment by TamasSzerb** [comment]
I see still this issue:

Initializing provider plugins...
- Reusing previous version of hashicorp/http from the dependency lock file
- Reusing previous version of hashicorp/kubernetes from the dependency lock file
- Reusing previous version of hashicorp/helm from the dependency lock file
- Reusing previous version of hashicorp/null from the dependency lock file
- Reusing previous version of hashicorp/external from the dependency lock file
- Reusing previous version of hashicorp/azurerm from the dependency lock file
- Reusing previous version of hashicorp/tls from the dependency lock file
- Installing hashicorp/kubernetes v1.13.3...
- Installed hashicorp/kubernetes v1.13.3 (signed by HashiCorp)
- Installing hashicorp/helm v1.3.2...
- Installed hashicorp/helm v1.3.2 (signed by HashiCorp)
- Installing hashicorp/null v3.0.0...
- Installed hashicorp/null v3.0.0 (signed by HashiCorp)
- Installing hashicorp/external v2.0.0...
- Installed hashicorp/external v2.0.0 (signed by HashiCorp)
**- Installing hashicorp/azurerm v2.92.0...
- Installed hashicorp/azurerm v2.92.0 (signed by HashiCorp)**
- Installing hashicorp/tls v3.0.0...
- Installed hashicorp/tls v3.0.0 (signed by HashiCorp)
- Installing hashicorp/http v2.0.0...
- Installed hashicorp/http v2.0.0 (signed by HashiCorp)

Terraform has been successfully initialized!

Error: deleting Azure Firewall Firewall: (Azure Firewall Name "[redacted]" / Resource Group "[redacted]") : network.AzureFirewallsClient#Delete: Failure sending request: StatusCode=415 -- Original Error: Code="UnsupportedMediaType" Message="The content media type '<null>' is not supported. Only 'application/json' is supported."

**Comment by byteknacker** [comment]
I upgraded to azurerm version 2.94.0 and still have the same issue with not being able to delete Azure Firewall
