### ISSUE TITLE
azurerm_linux_function_app requires both connection string and instrumentation key for app insights 

### ISSUE THREAD

**Issue by brennfoster** [hashicorp/terraform-provider-azurerm#16077]
Function Apps only require the instrumentation key to connect to Application Insights. There is no need to provide both a connection string and an instrumentation key.

│ Error: Missing required argument
│ 
│   with azurerm_linux_function_app
│   application_insights_key = var.app_insights_instrumentation_key
│ 
│ "site_config.0.application_insights_key": all of
│ `site_config.0.application_insights_connection_string,site_config.0.application_insights_key`
│ must be specified

**Comment by jschwellnus92** [comment]
This exact same issue exists for `azurerm_windows_function_app`

**Comment by tiagoboeing** [comment]
I fixed this passing `connection_string` too. The documentation doesn't show this as a required parameter (I know, is required only if Application Insights is being configured):

[![image](https://user-images.githubusercontent.com/3449932/162225359-35ac3901-2f63-4c9e-ab4e-8b7c30d72276.png)](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_function_app)

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_function_app

> But! If you use Application Insights and pass `application_insights_key` (`instrumentation_key`) the `application_insights_connection_string` will be required!

Configs example:

```tf
resource "azurerm_linux_function_app" "function_app" {
  ...

  site_config {
    application_insights_key               = azurerm_application_insights.application_insights.instrumentation_key
    application_insights_connection_string = azurerm_application_insights.application_insights.connection_string
  }

  ...
}
```

**Comment by kmadof** [comment]
I still have the same issue on **hashicorp/azurerm v3.2.0...**
