### ISSUE TITLE
azurerm_windows_function_app dotnet version not set correctly

### ISSUE THREAD

**Issue by royjia** [hashicorp/terraform-provider-azurerm#16417]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.8

### AzureRM Provider Version

3.2.0

### Affected Resource(s)/Data Source(s)

azurerm_windows_function_app

### Terraform Configuration Files

```hcl
resource "azurerm_windows_function_app" "fun-app" {
  name                        = "${local.name_slug}functionapp"
  location                    = azurerm_resource_group.rg.location
  resource_group_name         = azurerm_resource_group.rg.name
  service_plan_id             = data.azurerm_service_plan.asp.id
  storage_account_name        = azurerm_storage_account.sa.name
  storage_account_access_key  = azurerm_storage_account.sa.primary_access_key
  functions_extension_version = "~4"
  site_config {
    always_on = true
    scm_use_main_ip_restriction = "false"
    worker_count = 2
  
    application_stack {
      dotnet_version = "6"
    }
}
}
```

### Debug Output/Panic Output

```shell
Deploys without issue
```

### Expected Behaviour

The expected behavior is to deploy a windows function app with function runtime ~4. 

### Actual Behaviour

The actual result of deployment is runtime version "custom" and the only supported drop down is ~3. I'm assuming the reason for "custom"  is the function app was created with dotnet version 3.1 and does not support runtime ~4 only ~3, however I specified dotnet 6 in TF.  When I create manually in azure portal the function app is created with the correct dotnet 6. I can even import the manually created function app to the same resource in terraform state with no issues.

### Steps to Reproduce

Just try to create a function app using the new azurerm_windows_function_app with dotnet 6 and runtime ~4. 

I'm assuming the configuration for dotnet 6 is under application stack and runtime version is under functions_extension_version.

  functions_extension_version = "~4"
    application_stack {
      dotnet_version = "6"

I tried both options 3.1 and 6 (as documented) both yield the same result. 

### Important Factoids

no

### References

no

**Comment by mitchell-amasia** [comment]
Same here! :(

**Comment by RyanS-C** [comment]
Likewise, I have the same issue.

`PS C:\Users\ryan.stanley\Downloads\Function> terraform version
Terraform v1.1.9
on windows_amd64
+ provider registry.terraform.io/aztfmod/azurecaf v2.0.0-preview-2
+ provider registry.terraform.io/hashicorp/azurerm v3.3.0
+ provider registry.terraform.io/hashicorp/local v2.2.2`

Upon further investigation, I have found in the azure resource browser:
https://resources.azure.com/

The configuration `config` document has the following values when created using the `azurerm_windows_function_app` terraform resource: 

`       ...
        "netFrameworkVersion": **"v4.0"**,
        "phpVersion": "",
        "pythonVersion": "",
        "nodeVersion": "",
        "powerShellVersion": "",
        "linuxFxVersion": "",
        "windowsFxVersion": "DotNet|6",
        ...
`

Upon creating the resource manually via the azure ui/portal:

`
        "netFrameworkVersion": "v6.0",
        "phpVersion": "",
        "pythonVersion": "",
        "nodeVersion": "",
        "powerShellVersion": "",
        "linuxFxVersion": "",
        "windowsFxVersion": null,
`

** NOTE: the `netFrameworkVersion` and `windowsFxVersion` are different. I think that the later should be the correct values for this not the ones that are being created at present.

Upon manually updating the attributes via the eddittor the `~4` function version was available in the drop down.

**Comment by lrsvendsen** [comment]
I am experiencing the same problem with the azurerm_linux_function_app. Any updates on the triage?

**Comment by evandeworp** [comment]
I think the Terraform logic that checks/sets the value of WindowsFxVersion for Windows Function Apps isn't right (I've seen LinuxFxVersion mentioned in the documentation but not WindowsFxVersion - is WindowsFxVersion relevant at all to Windows Function Apps?).

For example, I created windows function apps with 4 different runtimes using powershell with debug enabled and the following is what Microsoft command line sends to Azure ARM - none of these calls set WindowsFxVersion:

dotnet 6:
`{
  "kind": "functionapp",
  "properties": {
    "siteConfig": {
      "netFrameworkVersion": "v6.0",
      "appSettings": [
        {
          "name": "FUNCTIONS_WORKER_RUNTIME",
          "value": "dotnet"
        },
        {
          "name": "FUNCTIONS_EXTENSION_VERSION",
          "value": "~4"
        },
      ],
    }
  }
}`

dotnet 3.1:
`{
  "kind": "functionapp",
  "properties": {
    "siteConfig": {
      "appSettings": [
        {
          "name": "FUNCTIONS_WORKER_RUNTIME",
          "value": "dotnet"
        },
        {
          "name": "FUNCTIONS_EXTENSION_VERSION",
          "value": "~3"
        },
      ],
    }
  }
}`

java 11:
`{
  "kind": "functionapp",
  "properties": {
    "siteConfig": {
      "netFrameworkVersion": "v6.0",
      "appSettings": [
        {
          "name": "FUNCTIONS_WORKER_RUNTIME",
          "value": "java"
        },
        {
          "name": "FUNCTIONS_EXTENSION_VERSION",
          "value": "~4"
        },
      ],
      "javaVersion": "11"
    }
  }
}`

node 14:
`{
  "kind": "functionapp",
  "properties": {
    "siteConfig": {
      "netFrameworkVersion": "v6.0",
      "appSettings": [
        {
          "name": "FUNCTIONS_WORKER_RUNTIME",
          "value": "node"
        },
        {
          "name": "WEBSITE_NODE_DEFAULT_VERSION",
          "value": "~14"
        },
        {
          "name": "FUNCTIONS_EXTENSION_VERSION",
          "value": "~4"
        },
      ],
    }
  }
}`

**Comment by neilmcalister** [comment]
There are numerous issues with this resource type over the old one - it also won't generate host keys either. https://github.com/hashicorp/terraform-provider-azurerm/issues/17750

I've switched back to the old resource azurerm_function_app - these new ones just don't work. The fact that this issue was raised in April and its now nearly August proves my point. I've no idea why these where introduced in this state.

**Comment by SrinivasAjimera** [comment]
Great job, I love this topic & especially the way you have explained it is really awesome. Thanks for sharing this info.	

https://espirittech.com/dot-net-application-development-company/

**Comment by JoshWeepie** [comment]
Same issue here, also see this link https://docs.microsoft.com/en-us/answers/questions/835272/azure-functions-pinned-to-unsupported-dotnet-runti.html that says it's fixable an ARM template by setting `"netframeworkversion": {"type": "string","defaultValue":"v6.0"}`.

**Comment by xiaxyi** [comment]
Thanks guys for raising the issue. For the newly created windows functions, we will set the .NetFrameworkVersion to v6.0 if dotnet_version sets to 6 in the TF config, it should fix the issue custom ~4. As mentioned in our [docs](https://techcommunity.microsoft.com/t5/apps-on-azure-blog/issues-you-may-meet-when-upgrading-azure-function-app-to-v4/ba-p/3288983), function runtime 4.0 requires the underlying .Net version6, if the functions are created before, please aslo set the .net version to 6 when upgrading the function worker runtime to 4 and it should resolve custom ~4 situation.

**Comment by CRhodes1510** [comment]
@xiaxyi I'm creating a new a Function as per your comment on the 24th Aug 2022 but still get the same warning and my netFrameworkVersion is "v4.0"
Goolging around the area, I don't think there is anything wrong with my code
https://github.com/CRhodes1510/Terraform/blob/main/WindowsFunctionApp.tf

Is there anything that screams incorrect? Any help would be greatly appreicated
Thanks :)

**Comment by xiaxyi** [comment]
@CRhodes1510 the fix is in the mentioned pr. Can you try setting that property via api and see if its working?

**Comment by CRhodes1510** [comment]
@xiaxyi setting via Azure CLI, works a treat :)

**Comment by SPALLADI** [comment]
It's not working for me with CLI commands. Just stuck with this issue.

**Comment by SPALLADI** [comment]
> It's not working for me with AZ CLI commands. Just stuck with this issue.



> @xiaxyi setting via Azure CLI, works a treat :)

It's not working for me with AZ CLI commands. Just stuck with this issue.

**Comment by SPALLADI** [comment]
Please someone help me with AZ CLI command. I can see ~4 is updated, but defaulted to custom field. Has anyone succeeded with the FUNCTIONS_EXTENSION_VERSION to ~4

**Comment by CRhodes1510** [comment]
Using the below Powershell code and executing as SPN in DevOps Azure CLI task, got rid of the warning for me

`az functionapp config set --name $(FunctionAppName) --resource-group $(ResourceGroupName) --net-framework-version v6.0`

**Comment by SSKLCP** [comment]
Is there any update on this? Ideally I just want to run the Terraform without needing the additional CLI step

**Comment by websolut** [comment]
We experience the same issue. It seems to be a pretty easy fix for TF azurerm to add another parameter similar to the app service resource. Thanks.

**Comment by kahawai-sre** [comment]
I'm using AzAPI provider to resolve any of these types of issues.

New deploy reference:

- https://learn.microsoft.com/en-us/azure/templates/Microsoft.Web/sites?pivots=deployment-language-terraform

Update existing example:

`resource "azapi_update_resource" "this" {
  type        = "Microsoft.Web/sites@2022-03-01"
  resource_id = azurerm_windows_function_app.fa-test-vnet-content2.id
  body = jsonencode({
    properties = {
      netFrameworkVersion = "v6.0"
    }
  })
}`

**Comment by xiaxyi** [comment]
@kahawai-sre @royjia , the issue should be fixed now, can you confirm if the app stack for windows dotnet function is set correctly? Thanks!

**Comment by rcskosir** [comment]
Thanks for taking the time to submit this issue. It looks like this has been resolved as of #19685. As such, I am going to mark this issue as closed.
