### ISSUE TITLE
Terraform plan with azurerm_dns_a_record fails when parsing existing dns record with azurerm 3.19.0

### ISSUE THREAD

**Issue by abreunig359** [hashicorp/terraform-provider-azurerm#18039]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.14.10

### AzureRM Provider Version

3.19.0

### Affected Resource(s)/Data Source(s)

azurerm_dns_a_record

### Terraform Configuration Files

```hcl
resource "azurerm_dns_a_record" "a_record" {
  name = "dns_name"
  records = [
    kubernetes_service.service_name.status[0].load_balancer[0].ingress[0].ip
  ]
  resource_group_name = "resource_group_name"
  ttl                 = 3600
  zone_name           = "zone_name"

  tags = local.tags
}
```

### Debug Output/Panic Output

```shell
Error: parsing "/subscriptions/uuid/resourceGroups/resourceGroup/providers/Microsoft.Network/dnszones/dnszone/A/record": parsing segment "staticDnsZones": expected the segment "dnszones" to be "dnsZones"
```

### Expected Behaviour

Terraform plan should finish successfully.
With azurerm 3.18.0 it works fine.
There where no changes to the dns config, aside from upgrading the provider version to 3.19.0

### Actual Behaviour

Terraform plan fails with parsing error.

### Steps to Reproduce

Run `terraform plan` or `terraform apply` with an existing dns_a_record after upgrading to azurerm 3.19.0

**Comment by wiebeck** [comment]
Same for CNAME record with provider version 3.19.0.

**Comment by hamza-tumturk** [comment]
Same here, this started occuring in the new provider version v3.19.0 for us as well.

**Comment by domenicomastrangelo** [comment]
I pushed a PR just now https://github.com/hashicorp/terraform-provider-azurerm/pull/18044

**Comment by hamza-tumturk** [comment]
@domenicomastrangelo is there any workaround available until release of the fix?

**Comment by domenicomastrangelo** [comment]
@hamza-tumturk you could downgrade the image to 3.18.0 as that seems to be working correctly

**Comment by epopisces** [comment]
Same with azurerm_dns_zone also:

> Error: parsing "/subscriptions/$subID/resourceGroups/rg-platformx-stg/providers/Microsoft.Network/dnszones/$dnsZone": parsing segment "staticDnsZones": expected the segment "dnszones" to be "dnsZones"
│  
│   with azurerm_dns_zone.this,

**Comment by Amier3** [comment]
Hey @abreunig359 

Thanks for the report and thanks to @domenicomastrangelo for the quick PR! We appreciate everyone adding context and upvoting this. We'll have to review and test the PR to see if it fully solves the root cause of the bug, but we'll keep everyone here updated once that's figured out.

As far as workarounds go, I recommend downgrading to 3.18.0 if this is affecting anyones environment.

**Comment by Amier3** [comment]
We've PR'd a fix in #18048  and will be rolling out a point release shortly.

**Comment by MarkDeVerno** [comment]
This is still happening for CNAME records:

> Error: parsing "/subscriptions/cd25a667-aee9-4704-be53-9c99a1008b55/resourceGroups/rg-dns/providers/Microsoft.Network/dnszones/mydns.com/CNAME/my_app": parsing segment "staticDnsZones": expected the segment "dnszones" to be "dnsZones"

**Comment by vishalsinha21** [comment]
We are using azurerm version 3.23.0 and faced this issue while deleting an A record. I thought this has been fixed in version  3.19.1 and shouldn't be happening in the higher versions 🤔 

```
Error: parsing "/subscriptions/***": parsing segment "staticDnsZones": expected the segment "dnszones" to be "dnsZones"
```

**Comment by jaritimonen** [comment]
Having this issue also with 3.23.0

**Comment by iqmetrix-cloudops** [comment]
Having this issue also with 3.24.0!

**Comment by LeePorte** [comment]
Still seeing this issue with 3.25.0

**Comment by kevinscollins** [comment]
We're having it with 3.26.0 as well

**Comment by ctienshi** [comment]
Issue is fixed with 3.27.0.

**Comment by TommyBeaton** [comment]
Just tried this and I'm still getting the same issue for CNAME with v 3.27.0 :'(

**Comment by tombuildsstuff** [comment]
@TommyBeaton if you're still seeing this in the most recent version of the provider you'll need to ensure the Resource ID being provided is in the correct format, the state migration will only fix existing resources upgrading to the new version - if the casing is defined incorrectly in the config you'll need to update this per the validation error message being returned.

**Comment by TommyBeaton** [comment]
I'm just pulling the resource ID from a resource declared above it `namespace_id = azurerm_servicebus_namespace.orbitalwitness.id`. So surely it will already be in the correct format?

**Comment by tombuildsstuff** [comment]
@TommyBeaton this issue's related to DNS Records, there isn't a field for Namespace ID in the DNS Resources, so this must be related to another resource?

**Comment by TommyBeaton** [comment]
Sorry, that was related to another issue I had earlier today 😅 Will investigate now

**Comment by kevinscollins** [comment]
@tombuildsstuff - this worked for me, thank you! 🙏
