### ISSUE TITLE
Terraform plan with azurerm_dns_a_record fails when parsing existing dns record with azurerm 3.24.0 

### ISSUE THREAD

**Issue by iqmetrix-cloudops** [hashicorp/terraform-provider-azurerm#18554]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.15.5

### AzureRM Provider Version

3.24.0

### Affected Resource(s)/Data Source(s)

azurerm_dns_a_record

### Terraform Configuration Files

```hcl
resource "azurerm_dns_a_record" "net_a_record_n_q" { 
    for_each = var.net_a_record_n_q
    name                = each.key
    zone_name           = azurerm_dns_zone.net_dnszone.name
    resource_group_name = "dns"
    ttl                 = 300 
   records             = each.value
}
```

### Debug Output/Panic Output

```shell
Error: parsing "/subscriptions/uuid/resourceGroups/resourceGroup/providers/Microsoft.Network/dnszones/dnszone/A/record": parsing segment "staticDnsZones": expected the segment "dnszones" to be "dnsZones"
```

**Comment by iqmetrix-cloudops** [comment]
@davidbiq

**Comment by ms-zhenhua** [comment]
Hi @iqmetrix-cloudops, thank you for reaching out.
The plan issue for azurerm_dns_a_record should have already been fixed by https://github.com/hashicorp/terraform-provider-azurerm/issues/18039. Could you kindly help double confirm your issue is caused by plan, not other operations(like **apply to delete**, etc...)?
If so, could you kindly provider a more detailed error messages which are output after you run **terraform plan** (you could remove any sensitive information)? Thanks.

**Comment by rolandjohann** [comment]
Can confirm that the issue is still present at
```
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "3.24.0"
    }
```
At my particular use case we change the name of a `azurerm_dns_zone` which results in delete and create.

**Comment by rolandjohann** [comment]
Just discovered that the changes are applied without errors. I assume that the state contains the wrong resource IDs. So a workaround can be to fix the casing issue there

**Comment by ms-zhenhua** [comment]
Hi @rolandjohann, @iqmetrix-cloudops, I have created a PR to fix this issue.
