### ISSUE TITLE
Add support for VS2022 Remote Debugging on Windows Web App

### ISSUE THREAD

**Issue by jthrasher-zag** [hashicorp/terraform-provider-azurerm#18580]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please add VS2022 as an available option for remote_debugging_version on azurerm_windows_web_app.  The Azure portal currently supports VS2017, VS2019, and VS2022 but the current provider only supports VS2017 and VS2019

```
╷
│ Error: expected site_config.0.remote_debugging_version to be one of [VS2017 VS2019], got VS2022
│ 
│   with azurerm_windows_web_app.change_notice,
│   on main.tf line 333, in resource "azurerm_windows_web_app" "change_notice":
│  333:     remote_debugging_version = "VS2022"
│ 
```

### New or Affected Resource(s)/Data Source(s)

azurerm_windows_web_app

### Potential Terraform Configuration

```hcl
resource "azurerm_windows_web_app" "example" {
  name                      = "example-web-app"
  resource_group_name       = azurerm_resource_group.example.name
  location                  = azurerm_resource_group.example.location
  service_plan_id           = azurerm_service_plan.example.id
  https_only                = true
  site_config {
    application_stack {
      current_stack  = "dotnet"
      dotnet_version = "v6.0"
    }

    ftps_state               = "Disabled"
    remote_debugging_enabled = true
    remote_debugging_version = "VS2022"
  }
}
```

**Comment by sven5** [comment]
This is till open?

**Comment by catriona-m** [comment]
Hi @sven5. It looks like this issue should have been resolved by #18684 and released in v3.28.0 of the provider. Could you share more details on your config and what versions you are using that might shed more light on what's gone wrong here? Thank you!

**Comment by rcskosir** [comment]
Thanks for taking the time to submit this issue. It looks like this has been resolved as of #18684. As such, I am going to mark this issue as closed. If that is not the case, please provide additional information including the version in which you are still experiencing this issue, thanks!

**Comment by Zaduvalo** [comment]
> Thanks for taking the time to submit this issue. It looks like this has been resolved as of #18684. As such, I am going to mark this issue as closed. If that is not the case, please provide additional information including the version in which you are still experiencing this issue, thanks!

Hi,
The issue is still not resolved. Linux and Windows Web Apps had missing VS2022 remote_debugging_version.

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_web_app#remote_debugging_version
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/windows_web_app#remote_debugging_version

https://github.com/hashicorp/terraform-provider-azurerm/pull/18684 - this task for Windows and Linux Function Apps.
