### ISSUE TITLE
Cannot convert SQL Database from provision compute to serverless due to invalid licence type

### ISSUE THREAD

**Issue by markjcarey** [hashicorp/terraform-provider-azurerm#21373]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.6

### AzureRM Provider Version

3.51.0

### Affected Resource(s)/Data Source(s)

azurerm_mssql_database

### Terraform Configuration Files

```hcl
resource "azurerm_mssql_database" "single_database" {
  name                           = example
  server_id                      = azurerm_mssql_server.server.id
  sku_name                       = var.sku_name
  license_type                   = substr(var.sku_name, 0, 4) != "GP_S" ? "BasePrice" : null
  collation                   = "SQL_Latin1_General_CP1_CI_AS" 
  storage_account_type        = "LRS"
  min_capacity                = 1
  auto_pause_delay_in_minutes = 60
}
```

### Debug Output/Panic Output

```shell
│ Error: serverless databases do not support license type
│ 
│   with module.sql-single.azurerm_mssql_database.single_database["aonportal-db"],
│   on ../../../../infra-repo-sql-db/main.tf line 161, in resource "azurerm_mssql_database" "single_database":
│  161: resource "azurerm_mssql_database" "single_database" {
│ 
╵
##[error]Terraform command 'apply' failed with exit code '1'.
##[error]╷
│ Error: serverless databases do not support license type
```

### Expected Behaviour

The database was originally provisioned as provisioned compute i.e. sku_name = GP_Gen5_2 with license_type set to 'BasePrice'.

When we change sku_name to serverless sku i.e. 'GP_S_Gen5_1' with licence_type set to null then we expect the database to be changed to the specified serverless type. 

### Actual Behaviour

We get the following error :

_Error: serverless databases do not support license type_

This error is coming from this resource : https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/mssql/mssql_database_resource.go

_if strings.HasPrefix(d.Get("sku_name").(string), "GP_S_") && d.Get("license_type").(string) != "" {
		return fmt.Errorf("serverless databases do not support license type")
}_

If we set the license_type to null it fails the above validation.  We can't set the licence type to an empty string either because then we get the following validation error : 

_expected license_type to be one of [BasePrice LicenseIncluded], got_ 

### Steps to Reproduce

1. Create an azurerm_mssql_database with provisioned compute sku  e.g. GP_Gen5_2 and license_type set to BasePrice.
2. Update the azurerm_mssql_database  with serverless SKU GP_S_Gen5_1 and license_type set to null or not set
3. An error is returned that serverless databases do not support license type

Note the following scenarios work fine 👍 

-  creating a new database with serverless SKU set
- Converting a database from serverless to provisioned compute sku
- Creating a new database with provisioned compute sku

This only appears to be an issue when converting from provisioned compute to serverless and the root cause seems to be updates made to the provider in latter half of last year. I assume the above validation code in the mssql_database_resource.go is the issue and needs to be updated to check for null rather than empty string but there may be a deeper issue.

### References

https://github.com/hashicorp/terraform-provider-azurerm/issues/15455

https://github.com/hashicorp/terraform-provider-azurerm/issues/17701

https://github.com/hashicorp/terraform-provider-azurerm/pull/19084

https://github.com/hashicorp/terraform-provider-azurerm/pull/18230

**Comment by aristosvo** [comment]
Trouble is probably caused by [this](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/mssql/mssql_database_resource.go#L536)..

It is a combination of the API which doesn't return the license at all times, a workaround to fix this and the introduction of serverless databases.

I'll try a few things, keep you posted!

**Comment by sinbai** [comment]
@aristosvo Since `license_type` is a `computed` and `optional` property, the result of `d.Get("license_type")` is `BasePrice` when updating the resource in this case. In fact, the result should be "". Since this property needs to be "computed" according to the behavior of the API, I'm assuming the following fix will resolve this issue. However, `d.GetRawConfig()` is not allowed to be used as far as I know, if you know of any alternative to d.GetRawConfig(), I think the problem might be solved by this way. Does it make sense?

![image](https://user-images.githubusercontent.com/39109137/231643049-64b0e52f-6d1d-44a9-8e0c-ab6f75615f7c.png)

**Comment by BenWaller** [comment]
As a workaround I've deleted the license type field from the state file to fix this issue.

**Comment by jaredbrogan** [comment]
The way I'm able to get around this is by doing the following:
1. Change SKU in Azure Portal to serverless.
2. Manually edit the state file and change the resource's `license_type` value to `""`
3. Re-run `terraform apply` and the issue is no longer presented.

**Comment by droyad** [comment]
Looks the same as #13209

**Comment by fotto** [comment]
I had the same issue after importing a pre-created database.

As workaround I've use a similar approach as suggested above (modifying terraform state).
When working with remote state the sequence is like this:

- terraform state pull > state_copy.tfstate
- then edit the local file: remove "license_type" from database definition and don't forget to increase the "serial" in the file
- terraform state push state_copy.tfstate

**Comment by sevak-mnatsakanyan** [comment]
Hi @aristosvo 
Seems the fix is merged, but I cannot find it in any release notes.

Is the fix released?

**Comment by amardeepakrazu** [comment]
Hi , circling back to this , is this bug fixed ? 
we still have an issue when we change to serverless tier , and we use reusable module for different internal teams to consume so we cannot afford to remove the license_type from  the module , cos only when we remove this value , its applies the serverless SKU. 
i.e after changing it via the portal ..
Any other alternative or fix released on this ?

**Comment by DenisBalan** [comment]
Same bug for us..

**Comment by aristosvo** [comment]
@amardeepakrazu Contact your Microsoft representative or Support and ask them to fix this in the API.

That is the only way forward I see here 😢

**Comment by stephybun** [comment]
Fixed by #26839
