### ISSUE TITLE
The `azurerm_key_vault_secret` resource wants to recreate the secret again after creation

### ISSUE THREAD

**Issue by kinseii** [hashicorp/terraform-provider-azurerm#22064]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.9

### AzureRM Provider Version

3.59.0

### Affected Resource(s)/Data Source(s)

azurerm_key_vault_secret

### Terraform Configuration Files

```hcl
resource "azurerm_key_vault_secret" "client_secret" {
  name            = "ad-application-client-secret"
  value           = local.client_secret
  key_vault_id    = data.azurerm_key_vault.terraform.id
}
```

### Debug Output/Panic Output

```shell
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # azurerm_key_vault_secret.client_secret will be created
  + resource "azurerm_key_vault_secret" "client_secret" {
      + id                      = (known after apply)
      + key_vault_id            = "/subscriptions/0fd6bfe3-*************************fe4f/resourceGroups/***********/providers/Microsoft.KeyVault/vaults/*************"
      + name                    = "ad-application-client-secret"
      + resource_id             = (known after apply)
      + resource_versionless_id = (known after apply)
      + value                   = (sensitive value)
      + version                 = (known after apply)
      + versionless_id          = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy
```

### Expected Behaviour

Terraform should not recreate an already created or imported resource

### Actual Behaviour

Terraform tries to create a new secret, even though there is a described secret in the state file

### Steps to Reproduce

terraform apply --auto-approve

**Comment by teowa** [comment]
Hi @kinseii , thanks for submitting this issue!
Seems I cannot reproduce this issue with [example configuration](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/key_vault_secret#example-usage), could you please share the details of the Key Vault? And from the provided configuration, the azurerm_key_vault_secret might refer to a Key Vault outside of Terraform management, is it possible for the Key Vault being deleted outside of Terraform after the Key Vault Secret being created?

**Comment by BHoggs** [comment]
Hi @teowa , we've been having the same issue and I've managed to find a reliable way to reproduce it.

It appears to be an issue when creating secrets cross-subscription. In theory this should work as we're referencing the full keyvault ID, but terraform seems unable to find the secret if they're in a different subscription. The provider has no problem creating the secret cross-sub, however.

This below example can reproduce the issue by using provider aliases between two subscriptions. This isn't how we're doing it in production, however seems good enough to reproduce the issue.

```terraform
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
  }
}

provider "azurerm" {
  features {}
  subscription_id = "<sub1>"
}

provider "azurerm" {
  features {}
  subscription_id = "<sub2>"
  alias           = "sub2"
}

data "azurerm_client_config" "current" {}

resource "azurerm_resource_group" "rg" {
  name     = "rg-kv-test"
  location = "australiaeast"
}

resource "azurerm_key_vault" "kv" {
  name                       = "bhtestkv4321"
  location                   = azurerm_resource_group.rg.location
  resource_group_name        = azurerm_resource_group.rg.name
  tenant_id                  = data.azurerm_client_config.current.tenant_id
  soft_delete_retention_days = 7
  purge_protection_enabled   = false

  sku_name = "standard"

  enable_rbac_authorization = true
}

resource "azurerm_role_assignment" "rbac" {
  scope                = azurerm_key_vault.kv.id
  role_definition_name = "Key Vault Secrets Officer"
  principal_id         = data.azurerm_client_config.current.object_id
}

resource "time_sleep" "wait_for_rbac" {
  create_duration = "30s"
  depends_on      = [azurerm_role_assignment.rbac]
}

resource "random_password" "password" {
  length = 24
}

resource "azurerm_key_vault_secret" "kvsecret" {
  depends_on = [time_sleep.wait_for_rbac]

  provider = azurerm.sub2

  name         = "my-secret"
  value        = random_password.password.result
  key_vault_id = azurerm_key_vault.kv.id
}
```

**Comment by pdoninv** [comment]
I want to confirm that the problem occurs when using alias at the resource provider and specifying a subscription other than the primary provider

**Comment by kinseii** [comment]
I want to confirm that the problem occurs when using alias at the resource provider and specifying a subscription other than the primary provider

**Comment by BHoggs** [comment]
@teowa This might be unrelated, but I've run into some other issues that lead me to believe there is a wider problem with how the provider is guessing the subscription for a given resource.

Came across this one today: I deployed an `azurerm_dns_zone` resource in the wrong subscription. So I updated the terraform `provider` block to change the `subscription_id` to the correct subscription. Note that no aliases are being used in this scenario.

As a result, terraform completely ignored the fact that the DNS zone did not exist in the new subscription - and even went ahead with updating some tags on the old resource in the old subscription. Terraform should have at least recognized that the resource did not exist in the new target subscription.

**Comment by teowa** [comment]
@BHoggs , there is differences between resources on how they get the subscription ID, manage-plane resources usually read subscription ID from their resource ID like in [format](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/dns_zone#import): 
> /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/mygroup1/providers/Microsoft.Network/dnsZones/zone1

But for data-plane resource, there is no subcription ID in their resource ID, so they read the subscription ID from provider. Example of data-plane resource ID, e.g. [Key Vault Secret](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/key_vault_secret#import):
> https://example-keyvault.vault.azure.net/secrets/example/fdf067c93bbb4b22bff4d8b7a9a56217

**Comment by LaurentLesle** [comment]
I have also the same problem when referencing a keyvault in a different subscription. Creation of a secret is working but on subsequent plan, I can see the refresh but Terraform track the resource as to-be-created. When I apply it says the resource already exist. 
Not sure we had that issue in the past. I am using the provider 3.56.0
My use case is customer centralise some shared secrets for VM in a different subscription.

**Comment by cutik** [comment]
I am having the same problem using azurerm 3.65
It is worth mentioning that it worked well on provider version 3.40

**Comment by b0bu** [comment]
same issue on 3.67

**Comment by alflig** [comment]
Same issue 3.74. We are currently using the ignore life cycle block on the terraform secret while waiting for an update.

**Comment by gtalaverareyes** [comment]
Same issue on 3.71.

**Comment by mangoleaf** [comment]
Same issue on 3.73.

Can we get an update on if anything is being done to fix this problem?

**Comment by teowa** [comment]
The source of this issue should be the current limitation of data plane resources (they have `https://` in [resource ID](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/key_vault_secret#import)), although `azurerm_key_vault_secret.key_vault_id` has subscription_id in it but during read/refresh it uses the subscription_id from the `provider` block. So if the `key_vault_id` and provider has different subscription, it cannot find its parent Key Vault thus mark itself as gone, then want it to be recreated.

For [various reasons](https://github.com/hashicorp/terraform-provider-azurerm/issues/21486#issuecomment-1516027759) it still cannot be easily solved now. So if you are using `alias` for provider block, please make sure the provider bind to the `azurerm_key_vault_secret` or `azurerm_key_vault_key` has the same `subscription_id` as the corresponding `azurerm_key_vault`.

 For example, in below config, please make sure `azurerm_key_vault_secret.kvsecret_1.key_vault_id` and `azurerm.sub1` have the same `subscription_id`.

```hcl

provider "azurerm" {
  features {}
  subscription_id = "<sub1>"
  alias           = "sub1"
}

provider "azurerm" {
  features {}
  subscription_id = "<sub2>"
  alias           = "sub2"
}

resource "azurerm_key_vault" "kv" {
  provider = "sub1"
  name     = "bhtestkv4321"
}

resource "azurerm_key_vault_secret" "kvsecret_1" {
   provider = "sub1"
   key_vault_id = azurerm_key_vault.kv.id
}


```

**Comment by penicaudm** [comment]
I know this issue is fairly old but we have a deployment that is impacted by this as well and it uses a module to deploy the resource, so its hard to use provider configuration on the resources. has anyone found a viable workaround? I tried re-writing the whole thing to move to a single subscription deployment but it's just too much work and issues to fix a terraform bug..

**Comment by asinitson** [comment]
Quite disappointing that we still have to deal with this 1 year after this was reported.

About the workarounds:
* ~~Setting provider on the `azurerm_key_vault_secret` resource in the module explicitly~~ - this didn't change anything.

* One workaround we managed to come up with in our team is this (still not tested since we didn't have time for refactoring - we found out the issue just yesterday, but it could work in theory):
    * Create intermediary Key Vault in the same subscription as the rest of the stuff (so you don't have to hop across subscriptions)
    * In the "target" subscription read secrets through data and "relay" them to a different Key Vault

* Yet another alternative could be (this is even uglier, I don't think we will be going that far for working around this.)
    * reading secrets via [the terraform_remote_state Data Source](https://developer.hashicorp.com/terraform/language/state/remote-state-data)
    * Adding secretes to the Key Vault in another state where default state is the same where Key Vault and Key Vault secretes are

**Comment by rhendr556** [comment]
Can we get an update on this issue please?

**Comment by peanutsguy** [comment]
Still present on 4.8

**Comment by a-schot** [comment]
This is still an issue on version 4.26.0

**Comment by michasacuer** [comment]
Can we get update on this?

**Comment by Red1971** [comment]
The issue is fixed in....

terraform {

  required_version = "~> 1.9.0"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "4.27.0"
    }

  }
}

**Comment by speedfreak01** [comment]
> The issue is fixed in....
> 
> terraform {
> 
> required_version = "~> 1.9.0"
> 
> required_providers { azurerm = { source = "hashicorp/azurerm" version = "4.27.0" }
> 
> } }

Still seeing the issue in 4.39.0 unless you can use provider alias's.

**Comment by Red1971** [comment]
> > The issue is fixed in....
> > terraform {
> > required_version = "~> 1.9.0"
> > required_providers { azurerm = { source = "hashicorp/azurerm" version = "4.27.0" }
> > } }
> 
> Still seeing the issue in 4.39.0 unless you can use provider alias's.

For me it only work by adding the provider to the TF code.


# Store the Application Registration Secret in Key-Vault  
```
resource "azurerm_key_vault_secret" "store_password" {
  depends_on = [azuread_application_password.pw]
  **provider            = azurerm.prod**
  count      = var.env == "devi" ? 1 : 0
  name       = "${local.sharepoint_display_name}-pw-sp"
  value      = azuread_application_password.pw[0].value
  key_vault_id = data.azurerm_key_vault.kv.id
  content_type = "Password for app registration '${local.sharepoint_display_name}' - client_id = ${azuread_application_registration.app_reg[0].client_id}"
  expiration_date = "2035-12-31T00:00:00Z"
  tags = var.tags_common_values
}
```

**Comment by speedfreak01** [comment]
Yeah, that will work fine and is the current work around / correct way of doing things to avoid issues.  

I suspect this issue is still open because there are potential use cases where not wanting to define a specific provider in the `azurerm_key_vault_secret` resource would be handy. I personally have one.
And because `azurerm_key_vault_secret` will still happily create a secret in a key vault even if it resides in a different subscription to the default provider. Its just that the read operation afterwards breaks due to limitations of data plane resources.

teowa has summed it up a few times already, this likely wont be easy to solve. https://github.com/hashicorp/terraform-provider-azurerm/issues/22064#issuecomment-1769799318

I only commented on your reply because i thought it was slightly misleading to state this was now fixed. :)

**Comment by Red1971** [comment]
No problem with your initial comment, I should have been clearer in my original comment....

Thanks
________________________________

**Comment by marcelovital** [comment]
Just confirming: I had the same issue, and the workaround of explicitly passing the provider/subscription fixed it. I just wish the error message was clearer, like "can't read the secret/check for existence when refreshing the state"
