### ISSUE TITLE
Resource ID validation for serverFarms element when referencing azurerm_service_plan resource

### ISSUE THREAD

**Issue by bdorplatt** [hashicorp/terraform-provider-azurerm#24727]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.4

### AzureRM Provider Version

3.89.0

### Affected Resource(s)/Data Source(s)

azurerm_service_plan azurerm_windows_function_app azurerm_windows_function_app_slot

### Terraform Configuration Files

There was a fix applied for the the deprecated app service plan/function app/function app slot resources in PR https://github.com/hashicorp/terraform-provider-azurerm/pull/24626

We are seeing the same issue with the non-deprecated equivalents of these resources. We are seeing "serverFarms" being parsed case sensitive as of provider version 3.88 and had to pin to 3.87 to get things going again as the problem persists in 3.89.

The resources we are using are:

```
azurerm_service_plan
azurerm_windows_function_app
azurerm_windows_function_app_slot
```

### Debug Output/Panic Output

**Error we are seeing if we reference a resource ID as "serverfarms" when building a resource based on azurerm_windows_function_app** 

```
│ The parsed Resource ID was missing a value for the segment at position 6
│ (which should be the literal value "serverFarms").
```

**Error we are seeing if we change the reference to "serverFarms" which allows the plan and apply to complete for the ASP and Function App but then fails on the apply for Windows Function App Slot creation:**

`│ Error: creating Windows Function App Slot: (Slot Name "dev" / Site Name "test-azf" / Resource Group "test-rg"): web.AppsClient#CreateOrUpdateSlot: Failure sending request: StatusCode=500 -- Original Error: Code="Failed" Message="The async operation failed." AdditionalInfo=[{"Message":"An error has occurred."}]`

### Expected Behaviour

Case for serverfarms element should be ignored

### Actual Behaviour

Deployment fails

**Comment by xiaxyi** [comment]
Hi @bargokr , Thanks for raising this issue, we migrated the SDK for azure service plan and the legacy app service plan so the resource ID use the camel case now, 3.89 is not supposed to receive the validation error after the [PR ](https://github.com/hashicorp/terraform-provider-azurerm/pull/24562)was merged, so can you confirm about the "serverFarms" validation error you received? 

Besides of the ID issue, would you mind sharing more details about the api error you got when you tried to create the app slot? can you share the config with me and can you try creating the slot in azure portal/ cli/ PowerShell, just to make sure the service plan & the app is in a healthy state and ready to host the slot. If this is an urgent issue and your production is being affected, I recommend opening a support ticket with MS support and provide your app's resource ID so the product group can check the status from the backend server. let me know if you have any question.

**Comment by bdorplatt** [comment]
@xiaxyi That PR only fixes things for the legacy resource. It doesn't appear the same was done for azurerm_service_plan. We can build a Service Plan and Function App if we reference the Service Plan Resource ID in camelCase or pull from the Service Plan ID from the Terraform output which is also camelCase.

`/subscriptions/11111111-1111-1111-1111-111111111111/resourceGroups/test-rg/providers/Microsoft.Web/serverFarms/test-asp`

Creating the azurerm_windows_function_app_slot resource fails with the error below. We are able to create the slot manually in the portal with no issue. This is only happening after the 3.88 provider. This is not a Microsoft issue.

`│ Error: creating Windows Function App Slot: (Slot Name "dev" / Site Name "test-azf" / Resource Group "test-rg"): web.AppsClient#CreateOrUpdateSlot: Failure sending request: StatusCode=500 -- Original Error: Code="Failed" Message="The async operation failed." AdditionalInfo=[{"Message":"An error has occurred."}]`

Tagging @tombuildsstuff and @jackofallops as they have worked some of the other issues relating to the SDK update where the camelCase has caused various other validation issues in other resources.

**Comment by tombuildsstuff** [comment]
@bdorplatt unfortunately this _is_ ultimately an API issue (since the API is returning a 500 for a valid value) - and as such that would need to be resolved by the Service Team (and as such I'm going to tag this `upstream/microsoft`).

The Azure API is _supposed_ to be case-insensitive in Requests and case-insensitive in Responses - however since the API is returning a 500 when providing the same value in a different casing - this issue would need to be resolved by the Service Team. @xiaxyi would you mind opening an ICM so that the Service Team can look into this?

**Comment by bdorplatt** [comment]
@tombuildsstuff Thank you for looking at this. Can any logic be added for the azurerm_windows_function_app_slot resource to get past this like has been done for other resources where this problem has arisen this week? Or is this a totally different issue?

**Comment by xiaxyi** [comment]
> @bdorplatt unfortunately this _is_ ultimately an API issue (since the API is returning a 500 for a valid value) - and as such that would need to be resolved by the Service Team (and as such I'm going to tag this `upstream/microsoft`).
> 
> The Azure API is _supposed_ to be case-insensitive in Requests and case-insensitive in Responses - however since the API is returning a 500 when providing the same value in a different casing - this issue would need to be resolved by the Service Team. @xiaxyi would you mind opening an ICM so that the Service Team can look into this?

I can open the icm, however, I think that may not be the good idea since the service team need the resource ID and other information that may contains the sensitive data, I don't think it's safe to share that information in an open platform like github. @bdorplatt Would you mind opening a support ticket and share your function app id with MS support engineer via internal channel, they will help to get the icm created.

**Comment by LoganHealy** [comment]
I think this issue is impacting all new function app slot builds on the latest version. I don't think this issue is on MS end, so MS ticket is not going to get anywhere.....

Provider version: 3.89.0

**Comment by bdorplatt** [comment]
I'm not sure why this is being pushed back on us to open a Microsoft case. This isn't specific to our deployment. @xiaxyi try building a Service Plan with a Function App and Function App slot with provider version 3.89 and you should be able to easily reproduce this error for troubleshooting.  I don't think this problem is getting the proper attention and is going to cause  problems for a lot of organizations once they move to the latest provider. This was a major breaking change introduce in provider version 3.88. I don't feel this should be the customer's responsibility to troubleshoot with Microsoft.

**Comment by xiaxyi** [comment]
@bdorplatt @LoganHealy I created the linux function app and the slot using the latest 3.90 provider but I didn't get the 500 error..

I used the simplest config as below:
```
azurerm_service_plan.test: Creating...
azurerm_service_plan.test: Still creating... [10s elapsed]
azurerm_service_plan.test: Still creating... [20s elapsed]
azurerm_service_plan.test: Creation complete after 20s [id=/subscriptions/85xxx/resourceGroups/xiaxin-asp-slot/providers/Microsoft.Web/serverFarms/xiaxinasp-newprovider]
azurerm_linux_function_app_slot.test: Creating...
azurerm_linux_function_app_slot.test: Still creating... [10s elapsed]
azurerm_linux_function_app_slot.test: Still creating... [20s elapsed]
azurerm_linux_function_app_slot.test: Still creating... [30s elapsed]
azurerm_linux_function_app_slot.test: Still creating... [40s elapsed]
azurerm_linux_function_app_slot.test: Still creating... [50s elapsed]
azurerm_linux_function_app_slot.test: Still creating... [1m0s elapsed]
azurerm_linux_function_app_slot.test: Still creating... [1m10s elapsed]
azurerm_linux_function_app_slot.test: Still creating... [1m20s elapsed]
azurerm_linux_function_app_slot.test: Still creating... [1m30s elapsed]
azurerm_linux_function_app_slot.test: Creation complete after 1m33s [id=/subscriptions/85xxx/resourceGroups/xiaxin-asp-slot/providers/Microsoft.Web/sites/xiaxintest-LFA-asp-slot/slots/xiaxintest-LFAS-asp]
```
I also tried to create the service plan using terraform azurerm 3.80 provider to create the slot then upgrade the provider to 3.90,  both new slot and existed slot that created using 3.80 can be updated without any issue.

By any chance that you can share your TF config with me so I can try again?

**Comment by bargokr** [comment]
> @bdorplatt @LoganHealy I created the linux function app and the slot using the latest 3.90 provider but I didn't get the 500 error..
> 
> I used the simplest config as below:
> 
> ```
> azurerm_service_plan.test: Creating...
> azurerm_service_plan.test: Still creating... [10s elapsed]
> azurerm_service_plan.test: Still creating... [20s elapsed]
> azurerm_service_plan.test: Creation complete after 20s [id=/subscriptions/85xxx/resourceGroups/xiaxin-asp-slot/providers/Microsoft.Web/serverFarms/xiaxinasp-newprovider]
> azurerm_linux_function_app_slot.test: Creating...
> azurerm_linux_function_app_slot.test: Still creating... [10s elapsed]
> azurerm_linux_function_app_slot.test: Still creating... [20s elapsed]
> azurerm_linux_function_app_slot.test: Still creating... [30s elapsed]
> azurerm_linux_function_app_slot.test: Still creating... [40s elapsed]
> azurerm_linux_function_app_slot.test: Still creating... [50s elapsed]
> azurerm_linux_function_app_slot.test: Still creating... [1m0s elapsed]
> azurerm_linux_function_app_slot.test: Still creating... [1m10s elapsed]
> azurerm_linux_function_app_slot.test: Still creating... [1m20s elapsed]
> azurerm_linux_function_app_slot.test: Still creating... [1m30s elapsed]
> azurerm_linux_function_app_slot.test: Creation complete after 1m33s [id=/subscriptions/85xxx/resourceGroups/xiaxin-asp-slot/providers/Microsoft.Web/sites/xiaxintest-LFA-asp-slot/slots/xiaxintest-LFAS-asp]
> ```
> 
> I also tried to create the service plan using terraform azurerm 3.80 provider to create the slot then upgrade the provider to 3.90, both new slot and existed slot that created using 3.80 can be updated without any issue.
> 
> By any chance that you can share your TF config with me so I can try again?

Can you please re-attempt this with **the windows function app / slot**? That is what is failing for us.

Config below (trimmed out some dynamic blocks that are not required). Not sure how helpful this is since its all variablized.

`
resource "azurerm_service_plan" "asp" {
  name                = "${var.tenant}-${var.region_abbr}-${var.subscription}-${var.asp_name_short}-asp"
  location            = var.region
  os_type             = var.asp_os_type
  resource_group_name = var.resource_group_name
  sku_name            = var.asp_sku_name
}  

resource "azurerm_windows_function_app" "function_app" {
  app_settings                = var.fa_app_settings
  builtin_logging_enabled     = var.fa_builtin_logging_enabled
  client_certificate_enabled  = var.fa_client_certificate_enabled
  client_certificate_mode     = var.fa_client_certificate_mode
  enabled                     = var.fa_enabled
  functions_extension_version = var.fa_extensions_version
  https_only                  = var.fa_https_only
  location                    = var.region
  name                        = "${var.tenant}-${var.region_abbr}-${var.subscription}-${var.fa_name_short}-azf"
  resource_group_name         = var.resource_group_name
  service_plan_id             = azurerm_service_plan.asp.id
  storage_account_access_key  = var.sa_primary_access_key
  storage_account_name        = var.sa_name
  virtual_network_subnet_id   = var.sn_id_vnet_integration

  site_config {
    always_on                              = var.fa_always_on
    application_insights_connection_string = var.ai_connection_string
      dynamic "ip_restriction" {
      for_each = var.fa_ip_restriction
      content {
        ip_address                = try(ip_restriction.value["ip_address"], null)
        service_tag               = try(ip_restriction.value["service_tag"], null)
        virtual_network_subnet_id = try(ip_restriction.value["virtual_network_subnet_id"], null)
        name                      = try(ip_restriction.value["name"], null)
        priority                  = try(ip_restriction.value["priority"], null)
        action                    = try(ip_restriction.value["action"], null)
        headers {
          x_azure_fdid      = try([ip_restriction.value["x_azure_fdid"]], null)
          x_fd_health_probe = try([ip_restriction.value["x_fd_health_probe"]], null)
          x_forwarded_for   = try([ip_restriction.value["x_forwarded_for"]], null)
          x_forwarded_host  = try([ip_restriction.value["x_forwarded_host"]], null)
        }
      }
    }

    dynamic "scm_ip_restriction" {
      for_each = var.fa_scm_ip_restriction
      content {
        action                    = try(scm_ip_restriction.value["action"], null)
        ip_address                = try(scm_ip_restriction.value["ip_address"], null)
        name                      = try(scm_ip_restriction.value["name"], null)
        priority                  = try(scm_ip_restriction.value["priority"], null)
        service_tag               = try(scm_ip_restriction.value["service_tag"], null)
        virtual_network_subnet_id = try(scm_ip_restriction.value["virtual_network_subnet_id"], null)
        headers {
          x_azure_fdid      = try([scm_ip_restriction.value["x_azure_fdid"]], null)
          x_fd_health_probe = try([scm_ip_restriction.value["x_fd_health_probe"]], null)
          x_forwarded_for   = try([scm_ip_restriction.value["x_forwarded_for"]], null)
          x_forwarded_host  = try([scm_ip_restriction.value["x_forwarded_host"]], null)
        }
      }
    }

    scm_use_main_ip_restriction = var.fa_scm_use_main_ip_restriction

    dynamic "cors" {
      for_each = var.fa_cors_enabled == "true" ? [var.fa_cors_enabled] : []
      content {
        allowed_origins       = var.fa_allowed_origins
        support_credentials   = var.fa_support_credentials
      }
    }

    default_documents           = var.fa_default_documents
    ftps_state                  = var.fa_ftps_state
    http2_enabled               = var.fa_http2_enabled
    managed_pipeline_mode       = var.fa_managed_pipeline_mode
    minimum_tls_version         = var.fa_minimum_tls_version
    use_32_bit_worker           = var.fa_use_32_bit_worker
    vnet_route_all_enabled      = var.fa_vnet_route_all_enabled
    websockets_enabled          = var.fa_websockets_enabled
    worker_count                = var.fa_worker_count

    application_stack {
      use_dotnet_isolated_runtime = var.fa_application_stack_type == "dotnet" ? var.fa_use_dotnet_isolated_runtime : null
      dotnet_version              = var.fa_application_stack_type == "dotnet" ? var.fa_dotnet_version : null
      java_version                = var.fa_application_stack_type == "java"? var.fa_java_version : null
      node_version                = var.fa_application_stack_type == "node" ? var.fa_node_version : null
      powershell_core_version     = var.fa_application_stack_type == "powershell" ? var.fa_powershell_core_version : null
      use_custom_runtime          = var.fa_application_stack_type == "custom" ? true : null
    }

    dynamic "app_service_logs" {
      for_each = var.fa_app_service_logs_enabled ? [1] : []
      content {
      disk_quota_mb           = var.fa_app_service_logs_disk_quota_mb
      retention_period_days   = var.fa_app_service_logs_retention_period_days
    }
   }
  }
}

resource "azurerm_windows_function_app_slot" "function_app_slot" {
  app_settings                = var.fa_slot_app_settings
  builtin_logging_enabled     = var.fa_slot_builtin_logging_enabled
  client_certificate_enabled  = var.fa_slot_client_certificate_enabled
  client_certificate_mode     = var.fa_slot_client_certificate_mode
  enabled                     = var.fa_slot_enabled
  function_app_id             = azurerm_windows_function_app.function_app.id
  functions_extension_version = var.fa_slot_extensions_version
  https_only                  = var.fa_slot_https_only
  name                        = var.fa_slot_name
  storage_account_access_key  = var.sa_primary_access_key
  storage_account_name        = var.sa_name
  virtual_network_subnet_id   = var.sn_id_vnet_integration

  site_config {
    always_on                              = var.fa_slot_always_on
    application_insights_connection_string = var.ai_connection_string
    dynamic "ip_restriction" {
      for_each = var.fa_slot_ip_restriction
      content {
        action                    = try(ip_restriction.value["action"], null)
        ip_address                = try(ip_restriction.value["ip_address"], null)
        name                      = try(ip_restriction.value["name"], null)
        priority                  = try(ip_restriction.value["priority"], null)
        service_tag               = try(ip_restriction.value["service_tag"], null)
        virtual_network_subnet_id = try(ip_restriction.value["virtual_network_subnet_id"], null)
        headers {
          x_azure_fdid      = try([ip_restriction.value["x_azure_fdid"]], null)
          x_fd_health_probe = try([ip_restriction.value["x_fd_health_probe"]], null)
          x_forwarded_for   = try([ip_restriction.value["x_forwarded_for"]], null)
          x_forwarded_host  = try([ip_restriction.value["x_forwarded_host"]], null)
        }
      }
    }

    dynamic "scm_ip_restriction" {
      for_each = var.fa_slot_scm_ip_restriction
      content {
        action                    = try(scm_ip_restriction.value["action"], null)
        ip_address                = try(scm_ip_restriction.value["ip_address"], null)
        name                      = try(scm_ip_restriction.value["name"], null)
        priority                  = try(scm_ip_restriction.value["priority"], null)
        service_tag               = try(scm_ip_restriction.value["service_tag"], null)
        virtual_network_subnet_id = try(scm_ip_restriction.value["virtual_network_subnet_id"], null)
        headers {
          x_azure_fdid      = try([scm_ip_restriction.value["x_azure_fdid"]], null)
          x_fd_health_probe = try([scm_ip_restriction.value["x_fd_health_probe"]], null)
          x_forwarded_for   = try([scm_ip_restriction.value["x_forwarded_for"]], null)
          x_forwarded_host  = try([scm_ip_restriction.value["x_forwarded_host"]], null)
        }
      }
    }

    scm_use_main_ip_restriction = var.fa_slot_scm_use_main_ip_restriction

    dynamic "cors" {
      for_each = var.fa_slot_cors_enabled == "true" ? [var.fa_slot_cors_enabled] : []
      content {
        allowed_origins       = var.fa_slot_allowed_origins
        support_credentials   = var.fa_slot_support_credentials
      }
    }

    default_documents           = var.fa_slot_default_documents
    ftps_state                  = var.fa_slot_ftps_state
    http2_enabled               = var.fa_slot_http2_enabled
    managed_pipeline_mode       = var.fa_slot_managed_pipeline_mode
    minimum_tls_version         = var.fa_slot_minimum_tls_version
    use_32_bit_worker           = var.fa_slot_use_32_bit_worker
    vnet_route_all_enabled      = var.fa_slot_vnet_route_all_enabled
    websockets_enabled          = var.fa_slot_websockets_enabled
    worker_count                = var.fa_slot_worker_count

    application_stack {
      use_dotnet_isolated_runtime = var.fa_slot_application_stack_type == "dotnet" ? var.fa_slot_use_dotnet_isolated_runtime : null
      dotnet_version              = var.fa_slot_application_stack_type == "dotnet" ? var.fa_slot_dotnet_version : null
      java_version                = var.fa_slot_application_stack_type == "java"? var.fa_slot_java_version : null
      node_version                = var.fa_slot_application_stack_type == "node" ? var.fa_slot_node_version : null
      powershell_core_version     = var.fa_slot_application_stack_type == "powershell" ? var.fa_slot_powershell_core_version : null
      use_custom_runtime          = var.fa_slot_application_stack_type == "custom" ? true : null
    }

    dynamic "app_service_logs" {
      for_each = var.fa_slot_app_service_logs_enabled ? [1] : []
      content {
      disk_quota_mb           = var.fa_slot_app_service_logs_disk_quota_mb
      retention_period_days   = var.fa_slot_app_service_logs_retention_period_days
    }
   }
  }
}
`

**Comment by xiaxyi** [comment]
@bargokr Thanks for the information, windows function app also works as expected:
```
azurerm_service_plan.test-windows: Still creating... [10s elapsed]
azurerm_service_plan.test-windows: Still creating... [20s elapsed]
azurerm_service_plan.test-windows: Creation complete after 27s [id=/subscriptions/85xxx/resourceGroups/xiaxin-asp-slot-380/providers/Microsoft.Web/serverFarms/xiaxinasp-380-windows]
azurerm_windows_function_app.test: Creating...
azurerm_windows_function_app.test: Still creating... [10s elapsed]
azurerm_windows_function_app.test: Still creating... [20s elapsed]
azurerm_windows_function_app.test: Still creating... [30s elapsed]
azurerm_windows_function_app.test: Still creating... [40s elapsed]
azurerm_windows_function_app.test: Still creating... [50s elapsed]
azurerm_windows_function_app.test: Still creating... [1m0s elapsed]
azurerm_windows_function_app.test: Creation complete after 1m19s [id=/subscriptions/85xxx/resourceGroups/xiaxin-asp-slot-380/providers/Microsoft.Web/sites/xiaxintest-WFA-asp-slot380]
azurerm_windows_function_app_slot.test: Creating...
azurerm_windows_function_app_slot.test: Still creating... [10s elapsed]
azurerm_windows_function_app_slot.test: Still creating... [20s elapsed]
azurerm_windows_function_app_slot.test: Still creating... [30s elapsed]
azurerm_windows_function_app_slot.test: Still creating... [40s elapsed]
azurerm_windows_function_app_slot.test: Still creating... [50s elapsed]
azurerm_windows_function_app_slot.test: Still creating... [1m0s elapsed]
azurerm_windows_function_app_slot.test: Still creating... [1m10s elapsed]
azurerm_windows_function_app_slot.test: Still creating... [1m20s elapsed]
azurerm_windows_function_app_slot.test: Creation complete after 1m23s [id=/subscriptions/85xxx/resourceGroups/xiaxin-asp-slot-380/providers/Microsoft.Web/sites/xiaxintest-WFA-asp-slot380/slots/xiaxintest-WFAS-asp380]
```
Have you tried update the windows function app slot using another client tool such as azure cli/ azure portal, just to make sure the slot is in a healthy state, so the issue can be narrowed down as well.

**Comment by bdorplatt** [comment]
Provider version 3.91 seems to have resolved this but we aren't able to find anything related specified in the release notes. Can someone identify which commit this fix was applied as part of? https://github.com/hashicorp/terraform-provider-azurerm/releases/tag/v3.91.0

**Comment by rcskosir** [comment]
:wave: @bdorplatt 
It looks like this has been resolved with [this part](https://github.com/hashicorp/terraform-provider-azurerm/commit/d66879a950c97d338ea8ae04b1328de1743a2296#diff-84dbea870148c5da0c41b833fbc39d58067ff337139f88efb0b5fdd08047974d) of the release: `commonids.ParseAppServiceEnvironmentIDInsensitively()`. As such, I am going to mark this issue as closed. If that is not the case, please provide additional information including the version in which you are still experiencing this issue, thanks!

**Comment by DamonStamper** [comment]
Still seeing this issue on AzureRM 3.97.1.

```
Error: parsing "/subscriptions/*ID*/resourceGroups/*RG*/providers/Microsoft.Web/serverfarms/*name*": parsing segment "staticServerFarms": parsing the AppServicePlan ID: the segment at position 6 didn't match

Expected a AppServicePlan ID that matched:

> /subscriptions/12345678-1234-9876-4563-123456789012/resourceGroups/example-resource-group/providers/Microsoft.Web/serverFarms/serverFarmValue

However this value was provided:

> /subscriptions/*ID*/resourceGroups/*RG*/providers/Microsoft.Web/serverfarms/*name*
```

I looked up https://github.com/search?q=repo%3Ahashicorp%2Fgo-azure-helpers%20staticServerFarms&type=code but can't tell how it's supposed to be case insensitive.
