### ISSUE TITLE
recovery_services_vault while setting up immutability with existing recovery service vault (LRS and GRS)

### ISSUE THREAD

**Issue by ghodkerahul** [hashicorp/terraform-provider-azurerm#25106]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.0

### AzureRM Provider Version

3.93.0

### Affected Resource(s)/Data Source(s)

azurerm_recovery_services_vault

### Terraform Configuration Files

```hcl
## the code for existing rsv

resource "azurerm_recovery_services_vault" "example" {
  location            = "westeurope"
  resource_group_name = "example"
  name                = "test-lrs-rv"
  sku                 = "Standard"
  storage_mode_type   = "LocallyRedundant"
  tags                = local.tags
  
 + immutability        = "Locked"
}
```

### Debug Output/Panic Output

```shell
Error: Plugin did not respond
plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may

github.com/hashicorp/terraform-provider-azurerm/internal/services/recoveryservices.resourceRecoveryServicesVaultUpdate(0x0?, {0x7a19160?, 0xc000b62480})
	github.com/hashicorp/terraform-provider-azurerm/internal/services/recoveryservices/recovery_services_vault_resource.go:578 +0x1b95
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0x922bad0?, {0x922bad0?, 0xc0031e7620?}, 0xd?, {0x7a19160?, 0xc000b62480?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:800 +0x163
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc001845420, {0x922bad0, 0xc0031e7620}, 0xc001771930, 0xc00155d500, {0x7a19160, 0xc000b62480})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:919 +0x83a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0009cf1a0, {0x922bad0?, 0xc0031e7530?}, 0xc0031d3950)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/grpc_provider.go:1060 +0xdbc
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc001cd65a0, {0x922bad0?, 0xc0031e6d20?}, 0xc000783960)
	github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/tf5server/server.go:859 +0x56b
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x85fb5e0?, 0xc001cd65a0}, {0x922bad0, 0xc0031e6d20}, 0xc0007838f0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:467 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002121e0, {0x9252ba0, 0xc001d331e0}, 0xc0031f0360, 0xc001d72990, 0xec16eb8, 0x0)
	google.golang.org/grpc@v1.58.3/server.go:1374 +0xde7
google.golang.org/grpc.(*Server).handleStream(0xc0002121e0, {0x9252ba0, 0xc001d331e0}, 0xc0031f0360, 0x0)
	google.golang.org/grpc@v1.58.3/server.go:1751 +0x9e7
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.58.3/server.go:986 +0xbb
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 14
	google.golang.org/grpc@v1.58.3/server.go:997 +0x145

Error: The terraform-provider-azurerm_v3.93.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

Error: Process completed with exit code 1.
```

### Expected Behaviour

It should enable immutable setting on RSV

### Actual Behaviour

plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may

### Steps to Reproduce

terraform apply

### Important Factoids

westeurope

**Comment by ziyeqf** [comment]
Hi @ghodkerahul, thanks for reporting.

I have opened a PR for this(https://github.com/hashicorp/terraform-provider-azurerm/pull/25132), once it merged & released this issue should be fixed. You can subscribe the PR to keep track on it.

Thanks

**Comment by ghodkerahul** [comment]
Hi got the same error 

Plugin did not respond
│ 
│   with azurerm_key_vault.sharediaaskv,
│   on keyvault.tf line 3, in resource "azurerm_key_vault" "sharediaaskv":
│    3: resource "azurerm_key_vault" "sharediaaskv" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
azurerm_recovery_services_vault.pl_recovery_vault: Modifying... [id=/subscriptions/xxx-xxx-xxx/resourceGroups/rg-rsv-platform-iaas-prod-weu-001/providers/Microsoft.RecoveryServices/vaults/rsv-platform-iaas-prod-weu-001]
Stack trace from the terraform-provider-azurerm_v3.90.0_x5 plugin:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7061295]
goroutine 88 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/recoveryservices.resourceRecoveryServicesVaultUpdate(0x0?, {0x7d947a0?, 0xc0015a4480})
	github.com/hashicorp/terraform-provider-azurerm/internal/services/recoveryservices/recovery_services_vault_resource.go:578 +0x1b95
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0x9592880?, {0x9592880?, 0xc002307590?}, 0xd?, {0x7d947a0?, 0xc0015a4480?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:800 +0x163
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0010dd260, {0x9592880, 0xc002307590}, 0xc001c83520, 0xc001f60880, {0x7d947a0, 0xc0015a4480})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:919 +0x83a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0009cfb48, {0x9592880?, 0xc0023074a0?}, 0xc001c5cff0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/grpc_provider.go:1060 +0xdbc
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0012a8a00, {0x9592880?, 0xc002241ec0?}, 0xc000195730)
	github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/tf5server/server.go:859 +0x56b
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x89[36](https://github.com/kesko-dev/kesko-azure-lz-iaas/actions/runs/8140607087/job/22246211191#step:7:37)0e0?, 0xc0012a8a00}, {0x9592880, 0xc002241ec0}, 0xc000195650, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:467 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002341e0, {0x95b8fe0, 0xc001c80000}, 0xc00225fe60, 0xc001c03470, 0xf12ee58, 0x0)
	google.golang.org/grpc@v1.58.3/server.go:1[37](https://github.com/kesko-dev/kesko-azure-lz-iaas/actions/runs/8140607087/job/22246211191#step:7:38)4 +0xde7
google.golang.org/grpc.(*Server).handleStream(0xc0002341e0, {0x95b8fe0, 0xc001c80000}, 0xc00225fe60, 0x0)
	google.golang.org/grpc@v1.58.3/server.go:1751 +0x9e7
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.58.3/server.go:986 +0xbb
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 12
	google.golang.org/grpc@v1.58.3/server.go:997 +0x1[45](https://github.com/kesko-dev/kesko-azure-lz-iaas/actions/runs/8140607087/job/22246211191#step:7:46)
Error: The terraform-provider-azurerm_v3.90.0_x5 plugin crashed!
This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by ghodkerahul** [comment]
> Hi @ghodkerahul, thanks for reporting.
> 
> I have opened a PR for this(#25132), once it merged & released this issue should be fixed. You can subscribe the PR to keep track on it.
> 
> Thanks
 Still getting the same issue we are using azurerm provider 3.90.0 do you think we need to upgrade it to 3.95.0?

**Comment by ziyeqf** [comment]
> Hi got the same error
> 
> Plugin did not respond │ │ with azurerm_key_vault.sharediaaskv, │ on keyvault.tf line 3, in resource "azurerm_key_vault" "sharediaaskv": │ 3: resource "azurerm_key_vault" "sharediaaskv" { │ │ The plugin encountered an error, and failed to respond to the │ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may │ contain more details. ╵ azurerm_recovery_services_vault.pl_recovery_vault: Modifying... [id=/subscriptions/xxx-xxx-xxx/resourceGroups/rg-rsv-iaas-prod-weu-001/providers/Microsoft.RecoveryServices/vaults/rsv-prod-weu-001] Stack trace from the terraform-provider-azurerm_v3.90.0_x5 plugin: panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7061295] goroutine 88 [running]: github.com/hashicorp/terraform-provider-azurerm/internal/services/recoveryservices.resourceRecoveryServicesVaultUpdate(0x0?, {0x7d947a0?, 0xc0015a4480}) github.com/hashicorp/terraform-provider-azurerm/internal/services/recoveryservices/recovery_services_vault_resource.go:578 +0x1b95 github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0x9592880?, {0x9592880?, 0xc002307590?}, 0xd?, {0x7d947a0?, 0xc0015a4480?}) github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:800 +0x163 github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0010dd260, {0x9592880, 0xc002307590}, 0xc001c83520, 0xc001f60880, {0x7d947a0, 0xc0015a4480}) github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:919 +0x83a github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0009cfb48, {0x9592880?, 0xc0023074a0?}, 0xc001c5cff0) github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/grpc_provider.go:1060 +0xdbc github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0012a8a00, {0x9592880?, 0xc002241ec0?}, 0xc000195730) github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/tf5server/server.go:859 +0x56b github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x89[36]0xc0012a8a00}, {0x9592880, 0xc002241ec0}, 0xc000195650, 0x0) github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:467 +0x169 google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002341e0, {0x95b8fe0, 0xc001c80000}, 0xc00225fe60, 0xc001c03470, 0xf12ee58, 0x0) google.golang.org/grpc@v1.58.3/server.go:1[37] google.golang.org/grpc.(*Server).handleStream(0xc0002341e0, {0x95b8fe0, 0xc001c80000}, 0xc00225fe60, 0x0) google.golang.org/grpc@v1.58.3/server.go:1751 +0x9e7 google.golang.org/grpc.(*Server).serveStreams.func1.1() google.golang.org/grpc@v1.58.3/server.go:986 +0xbb created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 12 google.golang.org/grpc@v1.58.3/server.go:997 +0x1[45]( Error: The terraform-provider-azurerm_v3.90.0_x5 plugin crashed! This is always indicative of a bug within the plugin. It would be immensely helpful if you could report the crash with the plugin's maintainers so that it can be fixed. The output above should help diagnose the issue.

Hi @ghodkerahul, the fixing PR has been merged and will be released on the provider v3.9.5.

**Comment by ghodkerahul** [comment]
> > Hi got the same error
> > Plugin did not respond │ │ with azurerm_key_vault.sharediaaskv, │ on keyvault.tf line 3, in resource "azurerm_key_vault" "sharediaaskv": │ 3: resource "azurerm_key_vault" "sharediaaskv" { │ │ The plugin encountered an error, and failed to respond to the │ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may │ contain more details. ╵ azurerm_recovery_services_vault.pl_recovery_vault: Modifying... [id=/subscriptions/xxx-xxx-xxx/resourceGroups/rg-rsv-iaas-prod-weu-001/providers/Microsoft.RecoveryServices/vaults/rsv-prod-weu-001] Stack trace from the terraform-provider-azurerm_v3.90.0_x5 plugin: panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7061295] goroutine 88 [running]: github.com/hashicorp/terraform-provider-azurerm/internal/services/recoveryservices.resourceRecoveryServicesVaultUpdate(0x0?, {0x7d947a0?, 0xc0015a4480}) github.com/hashicorp/terraform-provider-azurerm/internal/services/recoveryservices/recovery_services_vault_resource.go:578 +0x1b95 github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0x9592880?, {0x9592880?, 0xc002307590?}, 0xd?, {0x7d947a0?, 0xc0015a4480?}) github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:800 +0x163 github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0010dd260, {0x9592880, 0xc002307590}, 0xc001c83520, 0xc001f60880, {0x7d947a0, 0xc0015a4480}) github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:919 +0x83a github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0009cfb48, {0x9592880?, 0xc0023074a0?}, 0xc001c5cff0) github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/grpc_provider.go:1060 +0xdbc github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0012a8a00, {0x9592880?, 0xc002241ec0?}, 0xc000195730) github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/tf5server/server.go:859 +0x56b github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x89[36]0xc0012a8a00}, {0x9592880, 0xc002241ec0}, 0xc000195650, 0x0) github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:467 +0x169 google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002341e0, {0x95b8fe0, 0xc001c80000}, 0xc00225fe60, 0xc001c03470, 0xf12ee58, 0x0) google.golang.org/grpc@v1.58.3/server.go:1[37] google.golang.org/grpc.(*Server).handleStream(0xc0002341e0, {0x95b8fe0, 0xc001c80000}, 0xc00225fe60, 0x0) google.golang.org/grpc@v1.58.3/server.go:1751 +0x9e7 google.golang.org/grpc.(*Server).serveStreams.func1.1() google.golang.org/grpc@v1.58.3/server.go:986 +0xbb created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 12 google.golang.org/grpc@v1.58.3/server.go:997 +0x1[45]( Error: The terraform-provider-azurerm_v3.90.0_x5 plugin crashed! This is always indicative of a bug within the plugin. It would be immensely helpful if you could report the crash with the plugin's maintainers so that it can be fixed. The output above should help diagnose the issue.
> 
> Hi @ghodkerahul, the fixing PR has been merged and will be released on the provider v3.9.5.

@ziyeqf , Thanks for info. i thought it was covered with 3.94.0 but thanks for letting me know, will retry one 3.95.0 when available to use.
