### ISSUE TITLE
DELETE azurerm_storage_share Unable to delete share because one or more share snapshots have active leases

### ISSUE THREAD

**Issue by mpjtaylor** [hashicorp/terraform-provider-azurerm#26408]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.8.1

### AzureRM Provider Version

3.106.1

### Affected Resource(s)/Data Source(s)

azurerm_storage_share 

### Terraform Configuration Files

```hcl
resource "azurerm_storage_share" "files" {
  name                 = local.sharename
  quota                = var.file_share_quota
  access_tier          = var.backup_share_tier
  storage_account_name = data.azurerm_storage_account.files.name
}
```

### Debug Output/Panic Output

```shell
executing request: unexpected status 409 (409 Unable to delete share because one or more share snapshots have active leases. Release the share snapshot leases or delete the share with the include-leased parameter for x-ms-delete-snapshots.) with DeleteShareWhenSnapshotLeased: Unable to delete share because one or more share snapshots have active leases. Release the share snapshot leases or delete the share with the include-leased parameter for x-ms-delete-snapshots
```

### Expected Behaviour

File share should be deleted into soft delete state,

### Actual Behaviour

Azure errors cannot perform delete operation because following scope(s) are locked.

This is relatively new issue as we have been using this for along time

### Steps to Reproduce

terraform apply
terraform destroy

### Important Factoids

Storage account is backed up by Backup Vault

**Comment by magodo** [comment]
@mpjtaylor Thank you for submitting this issue! I've created a PR to update the underlying SDK. Once it's merged, we shall be able to *delete the share with the include-leased parameter for x-ms-delete-snapshots*.

**Comment by pc-learning-j** [comment]
When will this be merged and closed? I saw this has been in open state for few months. Currently I am facing the similar issue.

**Comment by aneeraj** [comment]
bump! @magodo any updates on when the related PR will be merged?

**Comment by magodo** [comment]
@aneeraj There is one typo in the previous PR, and I've submitted one more PR to fix that. This is to support the functionality via the data plane API.

Since currently there is a major change in the storage share, which changes it to use mgmt plane API: https://github.com/hashicorp/terraform-provider-azurerm/pull/27733. I've tried to dig into how its [delete API](https://github.com/magodo/azure-rest-api-specs/blob/d61e5beea1bac338cf3ef7c57560b4fc74f96b88/specification/storage/resource-manager/Microsoft.Storage/stable/2023-01-01/file.json#L449-L462) supports this use case. Unfortunately, I've met some issue using it. I've created an MSFT internal issue to ask for clarification.

**Comment by aneeraj** [comment]
Thanks for letting me know, @magodo. Appreciate it :)

**Comment by jaredbrogan** [comment]
Any update here? Just ran into the same issue, and it's coming up to a year since the last comment was made in this issue.

In the meantime for anyone else dealing with this, this is how you can resolve it using azure cli:
```
az storage share delete -n <share_name> --account-name <storage_account_name> --delete-snapshots include-leased
```

**Comment by aneeraj** [comment]
@magodo we were not facing this issue for a while and I was under the impression that it was fixed but we just started seeing failures again since last few days.

**Comment by Netkracker** [comment]
this is still happening on provider v4.81.0

With Microsoft's rollout of [Secure by default](https://learn.microsoft.com/en-us/azure/backup/secure-by-default?tabs=preview), soft delete is now always-on and cannot be disabled for Recovery Services vaults (GA across all regions). Backup vaults are following the same path via public preview.

The only viable destroy path for a recovery services vault holding backups seems to be using the [features](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/features-block) :

features {
  recovery_service {
    vm_backup_stop_protection_and_retain_data_on_destroy = true # or vm_backup_suspend_protection_and_retain_data_on_destroy
    purge_protected_items_from_vault_on_destroy          = true
  }
}

Using this on provider v4.81.0 you can successfully stop protection and purge protected items the vault itself destroys cleanly. But the storage share still can't be destroyed by Terraform. Even after the vault is gone, destroy fails with:

Error: deleting Share (Subscription: "<redacted>" Resource Group Name: "rg-test-cloud-33241" Storage Account Name: "statestqvg4o7ow" Share Name: "smbfileshare1"): unexpected status 409 (409 Conflict) with error: deleteShareWhenSnapshotLeased: Unable to delete share because one or more share snapshots have active leases. Release the share snapshot leases or delete the share with the include-leased parameter for x-ms-delete-snapshots.

Deleting manually via the portal or with  "az storage share delete --delete-snapshots include-leased" works fine but that means "terraform destroy" can never cleanly tear down the built resources without manual intervention.

Before "Secure by default" you could disable soft delete as a workaround. That option is now gone for Recovery Services vaults and is being phased out for Backup vaults too. Anyone using Azure Backup to protect file shares will hit this wall on destroy.


Any news here ?

**Comment by teowa** [comment]
The storage share deletion issue comes from limitations in the control plane API currently used by Terraform, which does not support the `include-leased` option. As a workaround for now, the storage share can only be deleted through the data plane API, and [az storage share delete](https://learn.microsoft.com/en-us/cli/azure/storage/share?view=azure-cli-latest#az-storage-share-delete) can be used.
