### ISSUE TITLE
importing container to fix issue #27942 fails with "expected the account "" to use  a domain suffix of "core.windows.net""

### ISSUE THREAD

**Issue by KezHalls** [hashicorp/terraform-provider-azurerm#29170]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

I am trying to resolve the issue that is listed here in by using storage acount id rather than storage account name 
https://github.com/hashicorp/terraform-provider-azurerm/issues/27942

I can confirm that
- am not using a custom domain (configured with standard domain suffix)
- I have the correct storage account and resource id.  (I retrieved from state file prior to removal)
-  I am working in the correct subscription.

### Terraform Version

1.11.2

### AzureRM Provider Version

3.113.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_container

### Terraform Configuration Files

```hcl
terraform state rm module.storage_account.azurerm_storage_container.mycontainer
terraform import module.storage_account.azurerm_storage_container.mycontainer /subscriptions/xxxx/resourceGroups/xxxx/providers/Microsoft.Storage/storageAccounts/xxxx/blobServices/default/containers/mycontainer
```

### Debug Output/Panic Output

```shell
n/a
```

### Expected Behaviour

Removal of container 
and
Successful re-import into state file

### Actual Behaviour

 Error: parsing account : /subscriptions/xxxx/resourceGroups/xxxx/providers/Microsoft.Storage/storageAccounts/xxxx/blobServices/default/containers/mycontainer: expected the account "" to use a domain suffix of "core.windows.net"

### Steps to Reproduce

terraform state rm module.storage_account.azurerm_storage_container.mycontainer
terraform import module.storage_account.azurerm_storage_container.mycontainer /subscriptions/xxxx/resourceGroups/xxxx/providers/Microsoft.Storage/storageAccounts/xxxx/blobServices/default/containers/mycontainer

**Comment by davejhahn** [comment]
I am also running into this and I'm not sure what the cause is.  I have checked the ids multiple times and everything looks as expected.

**Comment by magodo** [comment]
@KezHalls  https://github.com/hashicorp/terraform-provider-azurerm/issues/27942 is fixed in v4.20.0, while you are using the v3.113.0 of the provider.

Per the [document of v3.113.0](https://registry.terraform.io/providers/hashicorp/azurerm/3.113.0/docs/resources/storage_container#import), you shall import using the URL:

> terraform import azurerm_storage_container.container1 https://example.blob.core.windows.net/container

In case you want to migrate the container resource to using management plane API only, please upgrade the provider version to >= v4.20.0, then follow its document to import using its ARM id.

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @magodo‘s response as an answer. If you have future questions, I suggest using the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).

**Comment by KezHalls** [comment]
HI there, sorry I was only just able to get back to this.  I obviously misinterpreted the other case.   But I am still unable to import.  Have made azurerm latest version and now I get the `subscription_id` is a required provider property when performing a plan/apply operation.  I do have this in my code (even tried hardcoding)

![Image](https://github.com/user-attachments/assets/852071a6-06ac-4a84-9b43-3faf7a6042f4)

**Comment by magodo** [comment]
@KezHalls Probably you missed another aliased provider config?

**Comment by KezHalls** [comment]
damn.  was looking right at it.  thanks all working now.
